### ISSUE TITLE
Links in messages to external sites should open in a new window (tab)

### ISSUE THREAD

**Issue by jonearley** [SpaceTalk/SpaceTalk#108]

**Comment by dstollie** [comment]
Hmm I dont understand this one. Are you willing to explain further?

**Comment by jonearley** [comment]
@dstollie Say a message post has a link, then someone clicks on that link it currently opens in the same window. It would be a better user experience if the link opened in a new tab. Anyway, that is how Slack handles message links.

**Comment by lb-** [comment]
I think it would be better to clarify this as:

**Links in _messages_ to external sites should open in a new window (tab)**

Links in messages to internal pages/resources (such as channels or users) should **NOT** open in a new window (tab).

### Support of this approach:

---

In general the best approach is to NOT open anything in a new window, except for the exceptions;

> A Good Reason: The user is working on something on the page, that might be lost if the current page changed.
> https://css-tricks.com/use-target_blank/
> 
> ... the link may interrupt an ongoing process.
> http://www.smashingmagazine.com/2008/07/01/should-links-open-in-new-windows/

**Comment by dstollie** [comment]
I agree.. i labelled this one for 0.2.1 the version after the package migration!

**Comment by jonearley** [comment]
@lb- I agree.

**Comment by dstollie** [comment]
fixed
