### ISSUE TITLE
Generate Error Messages on the Client

### ISSUE THREAD

**Issue by lb-** [SpaceTalk/SpaceTalk#112]
Trello card: https://trello.com/c/ehJfaysD/65-re-style-sweet-alerts-to-conform-to-space-talk-core-design

To conform to the Meteor style guide (and for future i18n) it is better to generate error messages on the client as per this guide: https://github.com/meteor/meteor/wiki/Meteor-Style-Guide#generate-error-messages-on-the-client-not-on-the-server

> Right: In the event of failure, the server returns a symbolic error code, 'no-such-user', 'site-not-found', or 'access-denied'. The client then looks up that error code in a table to get an appropriate message and displays it to the user.

**Comment by lb-** [comment]
Rough example of a potential approach;

``` js

displayAlert = function (errorCode) {
  //should maybe validate that errorCode was provided?
  var errorOptions = errorMessages(errorCode) || errorMessages('default');
  swal(errorOptions);
};

errorMessages = {
  //using functions as we will probably want more flexibility in the future
  'default': function () {
    return {
      title: 'Yikes! Something went wrong',
      text: '',
      type: 'error'
    };
  },
  'message-deleted': function () {
    // https://github.com/SpaceTalk/SpaceTalk/blob/3d825c4710f49f948e490beaa2017c673787a66a/client/views/message/message.js#L153
    return {
      title: 'Message deleted',
      text: 'Message deleted successfully',
      type: 'success'
    };
  },
  'user-offline': function () {
    // https://github.com/SpaceTalk/SpaceTalk/blob/cb193d027bc3e1b362ec065f24d7d569fa1e68e9/client/views/channel/channel.js#L25
    return {
      title: 'Yikes! Something went wrong',
      text: "We can't complete your request at the moment, are you still online?",
      type: 'error'
    };
  },
  'user-not-allowed': function () {
    // https://github.com/SpaceTalk/SpaceTalk/blob/cb193d027bc3e1b362ec065f24d7d569fa1e68e9/client/lib/utilities.js#L70
    // note: there is already a displayUnauthorizedError function but using the above text
    // have assumed this is the start of a central error displaying function
    return {
      title: 'Yikes! Something went wrong',
      //text should probably be something like 'You are unauthorised to do this'
      text: "We can't complete your request at the moment, are you still online?",
      type: 'error'
    };
  }
};

```

**Comment by lb-** [comment]
Meteor methods would need to be re-worked to return error symbol eg.
https://github.com/SpaceTalk/SpaceTalk/blob/63470d38184f7f61596f2a78635ebec2f119caf0/server/methods/messages/delete.js

would become

``` js
Meteor.methods({
    'messages.delete': function (messageId) {
        check(messageId, String);
        if (!this.userId) {
            throw new Meteor.Error(401, 'user-not-allowed');
        }

        if (!Messages.findOne(messageId)) {
            throw new Meteor.Error(404, 'message-not-found');
        }

        if(isOwner('Messages', messageId)) {
            Messages.remove(messageId);
        }
    }
});

```

**Comment by rclai** [comment]
[The docs](http://docs.meteor.com/#/full/meteor_error) and the style guide are somewhat ambiguous. Is the error code the first parameter of the `Meteor.Error` object, by which they say in the style guide to use as the lookup key in the error code dictionary, or the second parameter? Initially I thought it was the first given that in the style guide they say NOT to return an HTTP status code. From what I'm understanding from the style guide, they want you to return `throw new Meteor.Error('channel-not-found')`?

**Comment by rclai** [comment]
I think this is something we need to post as an issue to the Meteor's Github repo because it is not very clear from both docs.

**Comment by lb-** [comment]
@rclai done https://github.com/meteor/meteor/issues/4478

However, in writing the issue, I think that the methods returning `throw new Meteor.Error('channel-not-found')` makes sense but that means there is no need for the reason variable to be provided ever (unless you make it null to provide the third arg - details.

**Comment by lb-** [comment]
If nothing comes through on Meteor issues, might post a question on the forum.

**Comment by dstollie** [comment]
@lb- and @rclai are there already some improvements regarding this issue?

**Comment by rclai** [comment]
You mean if MDG has gotten back to us? No. It's the weekend. They won't get back to us until at least Monday.

**Comment by lb-** [comment]
@dstollie MDG have replied, essentially the practice of using http codes is no longer advised. With `error` being a kind of error code, consistent and not presented to the user, and the `reason` being a human readable version of the code, again not provided to the user. There should be a client side way to present an actual error message to the user. MDG will hopefully update the docs in the future to be more clear about this approach.

so the above code should change to:

```
Meteor.methods({
    'messages.delete': function (messageId) {
        check(messageId, String);
        if (!this.userId) {
            //Meteor.Error(error - short and for developers only, reason - human readable, for developers only)
            throw new Meteor.Error('user-not-signed-in', 'User must be signed in to comment.');
        }

        if (!Messages.findOne(messageId)) {
            throw new Meteor.Error('message-not-found', 'Message not found, id provided: ' + messageId);
        }

        if(isOwner('Messages', messageId)) {
            Messages.remove(messageId);
        }
    }
});
```

**Comment by rclai** [comment]
We should then create a dictionary table since we need to eventually do i18n.

**Comment by lb-** [comment]
@rclai would you like me to start on this (new `/feature` branch) and submit a pr when done? not sure I will get time but will give it a shot in the next 24hrs

**Comment by rclai** [comment]
Go ahead.

**Comment by arpan10** [comment]
Should I pick this one up?

@lb-, I like the structure of your rough approach. However, since we are doing this partly to make localisation easier, I think instead of calling the object errorMessages, we should call it messages. It will contain all the possible strings that we will be using.

The displayAlert should pass the string-code to messages to fetch the correct set of strings.

This will provide a framework for the localisation as well as error message.

**Comment by lb-** [comment]
sure go for it. Away for the next two weeks so will not get a chance to do
any more. Thanks


## 

|b

+61 414 446 068
@_lb_ http://twitter.com/_lb_ | fb.me/lb.ben | lb.ee

**Comment by arpan10** [comment]
I've done the first pass of this.

Pull Request: https://github.com/SpaceTalk/SpaceTalk/pull/125
