### ISSUE TITLE
SpaceTalk features in readme

### ISSUE THREAD

**Issue by dstollie** [SpaceTalk/SpaceTalk#115]
A list of features SpaceTalk has would give newcomers a better idea of SpaceTalk. Could someone maybe start of with a list of features for in the readme? Whenever new features are being added the readme should be updated.

What do you guys think of this idea?

**Comment by lb-** [comment]
Love it! suggested starting point

# Features

## Currently Implemented
- Teams (group users into separate teams)
- Channels (each group contains multiple channels)
  - Remove/edit channels
  - Pinned items
  - Channel purpose (description) 
- Users
  - Gravatar for profile pictures
  - Online status
  - Self sign up 
- Messages
  - Emoji, Markdown support
  - Edit & trash your own messages
  - Direct Messaging between users
  - Indication of user typing
  - Rich embeds via https://iframely.com/

## On The Way
- Pinned messages
- Better notifications
- Packages structure (for extensibility)
- See the [roadmap](https://trello.com/b/R9Nh1V3t/spacetalk-roadmap) for more and get involved with bringing these features to life

**Comment by dstollie** [comment]
@lb- Nice starting point yeah! Could you submit it as a pr. Im unfortunately really busy with my graduation.

**Comment by lb-** [comment]
@dstollie done :smile:
