### ISSUE TITLE
User can change message timestamp and userId

### ISSUE THREAD

**Issue by SachaG** [SpaceTalk/SpaceTalk#119]
Just wanted to point out that it's currently possible to change a message's timestamp and userId via the browser console on http://spacetalk.meteor.com/

**Comment by nabiltntn** [comment]
@SachaG Even if it's the owner of the message ?

**Comment by SachaG** [comment]
If you're _not_ the owner, you can't change anything. But even if you _are_ the owner, you should not be able to change those properties, because that lets you fake the timestamp or assign the message to somebody else.

**Comment by nabiltntn** [comment]
OK, gonna fix it
