### ISSUE TITLE
Users online status

### ISSUE THREAD

**Issue by kevincharm** [SpaceTalk/SpaceTalk#13]
Working on users' online status && listing them in the sidebar

**Comment by kevincharm** [comment]
Just realised I should've waited til we converted to BlazeComponents D:! gonna re-code this fresh tomorrow

**Comment by rclai** [comment]
The `develop` branch was already using Blaze Components.

**Comment by kevincharm** [comment]
Yeah I know, I cloned it before you started

**Comment by rclai** [comment]
Oh ok.

**Comment by dstollie** [comment]
merged
