### ISSUE TITLE
How does it compare with Rocket.Chat?

### ISSUE THREAD

**Issue by mitar** [SpaceTalk/SpaceTalk#130]

**Comment by shtefcs** [comment]
I think rocket.chat is far far further with features and development than space.talk. And honestly my favorite was a spacetalk

**Comment by timbrandin** [comment]
Rocket.chat has chosen to be more of a Slack clone, SpaceTalk is investigating patterns that differentiates it from being another clone just like that. This is my view of the matter.

**Comment by engelgabriel** [comment]
I just want to emphasise that "Rocket.chat has chosen to be more of a Slack clone" is @timbrandin personal "view of the matter" and not at all shared by the Rocket.Chat team :)

You can enter our https://demo.rocket.chat and talk to the team if you want to know more about our long term plan.

**Comment by timbrandin** [comment]
I should also advice @engelgabriel to stop bothering me on joining their project, also this is not the place to advertise another application.

**Comment by engelgabriel** [comment]
Sorry, I though @mitar specifically mentioned Rocket.Chat on the question.

**Comment by mitar** [comment]
This is a pretty non-constructive comparison and really not helpful. :-(
