### ISSUE TITLE
Bootstrap support

### ISSUE THREAD

**Issue by dstollie** [SpaceTalk/SpaceTalk#2]
As discussed on https://trello.com/c/q2cx1oYh. We would want bootstrap support for SpaceTalk.

**Comment by dcsan** [comment]
would be nice to not make this a core dep tho. for mobile at least, bootstrap is a pretty clanky front end and a lot of fat.

sidenote: discussions on trello or here? this seems easier to track.

**Comment by dstollie** [comment]
This is wat i've written somewhere on the trello board:

I think we should pick a css framework.. you really dont want to create your own grid structure if you dont have to. Besides spacetalk is in its startup and the only ui we have is Slack. Later on we probably want to customize our theme and seriously we dont want to redesign all those components. I would say first stick to bootstrap modify the design like its more like slack and after that customize it more like we want it! 

Though we could pick another foundation is not so broadly supported as bootstrap with all most packages who offer standard gui components. Bootstrap has a pretty strong grid imho.. Besides that I want to make a quick start and bootstrap is the right tool for that I think.

Do you have other suggestions?

@dcsan once there is github issue about it we better start discussing it on github.. like you said trackign is easier and a bigger community will read it.

edit:
I was just reading about UIKit(http://getuikit.com/) which look really promising and has a really aweomse basic layout.
Here is a blog item about the comparison:
http://www.eugenesivokon.com/why-uikit-is-better-than-twitter-bootstrap

**Comment by dcsan** [comment]
not sure we need a full on CSS framework here - there are no forms or other web app stuff? we could keep it light and that means people are free to use/customize with different UI Kits.

Slack is different cos of all the nice touches. to that end, the best chat like CSS UI i've seen is this:
https://rawgit.com/IjzerenHein/famous-flex-chat/master/dist/index.html
that requires famous, so its probably a lot of baggage/complexity to bring into the project, but it does look/feel great.

this is also cute
http://tympanus.net/Development/CreativeGooeyEffects/index.html

I listed a bunch of CSS f/e options here:
http://stackoverflow.com/questions/23899318/meteor-with-mobile-front-end-ui-framework

I still think bootstrap is too much fat for not enough benefit, however most people are familiar with it. It's like the PHP of f/e frameworks.

**Comment by rclai** [comment]
We should not make it look like Slack, otherwise we're going to have the same issue that Libreboard had.

**Comment by camilosw** [comment]
I'm not working on this project, just keeping an eye on it, but what about this https://almsaeedstudio.com/themes/AdminLTE/index2.html? It use Bootstrap and looks a few like Slack.

**Comment by rclai** [comment]
The look is cool, but it probably comes with way too much stuff than we need right?

**Comment by dcsan** [comment]
> we're going to have the same issue that Libreboard had

i haven't been following .. like what? 
That seems like a nice project, but not sure why I would use it unless i was paranoid about data. 
Good as a hobby coding exercise but not useful as a project until it looks less like an identical clone?

> The look is cool, but it probably comes with way too much stuff than we need right?

which one? famous could complicate things I guess. Someone who's great with CSS can probly get 80% of the effect just by inserting divs and plain CSS.

**Comment by dcsan** [comment]
> We should not make it look like Slack

this maybe straying more into discussion for trello/forums? I personally would like to be involved in a next-gen slack but thats different project from "lets clone slack". What are the areas where this project is going to simply and clearly differentiate? Enough that would make people want to clone and use this app internally, rather than just opening a slack room.
- an easy to use "bot builder" UI could be really cool
- unlimited integrations for free
- what else?

**Comment by rclai** [comment]
Libreboard started out as MeTrello and was an identical clone of Trello. Trello issued a takedown request. They were forced to take down their code. Since then, they self-hosted their Git repo and re-designed their entire thing.

**Comment by newswim** [comment]
I think hand-rolling wouldn't take too long if we divided up the work and developed a style guide first (and picked a preprocessor). I would vote against Bootstrap, it adds a lot of padding to everything and is just a big 8000 line css file. The media queries are easy to rip out without depending on an entire library.

**Comment by ramsaylanier** [comment]
I'm totally with dcasn - I think any prevalent CSS framework is going to be over kill for this.  CSS frameworks are for developing apps when you don't have skilled front-end devs. We have access to those. Rolling a decent grid system is pretty easy - especially if we use flexbox (we should also have a conversation about targeted browser support). 

I understand using bootstrap to iterate quickly, but in the long run it's going to take more time to implement bootstrap and then later replace it with something custom.

**Comment by emlama** [comment]
I'm jumping on the we don't need bootstrap bandwagon. Besides having talented front-end devs to work on this project bootstrap is really overkill for a chat application and we won't use most of what it provides.

That being said, I think there's a lot we can learn from bootstrap. It would be great if there was a single settings.scss file that an end user could alter to customize their install of spacetalk.

**Comment by ramsaylanier** [comment]
I definitely think user customization or theming should be a thing, but should probably be lower on the roadmap for now. However, when building the css structure we should keep in mind that the end goal will be user customization.

**Comment by dcsan** [comment]
> It would be great if there was a single settings.scss file

agreed on one file but -

can we use stylus? I've found all the sass implementations for meteor really suck whereas stylus is supported by MDG.
I also personally much prefer stylus syntax, tho that maybe is an opinion

the main reason for sass is if you're using a legacy framework (like ionic/bootstrap) that requires it, otherwise it's time to move on!

**Comment by ramsaylanier** [comment]
Personally I think SASS is the way to go, mainly because it is probably
more maintainble and there are generally more resources out there for it.

**Comment by rclai** [comment]
Sass has already been chosen.

**Comment by rclai** [comment]
In addition, it looks like the consensus is that we are going to design the UI from scratch.

**Comment by rclai** [comment]
And probably have some base normalized super basic backbone of some sort to start with I guess. Cc @timbrandin @dstollie

**Comment by dcsan** [comment]
> Sass has already been chosen.

or just noone thought about it and we ended up with that as a default? 
The sass plugin caused endless hassle on the meteoric project.

**Comment by ramsaylanier** [comment]
Are you referring to the fourseven:scss package? I see that is included in SpaceTalk - personally I don't use it (I use gulp to compile, autoprefix, and minify my scss), but it shouldn't have actually caused that many problems if you were using it properly.

**Comment by dcsan** [comment]
https://github.com/meteoric/ionic-sass/issues/1
https://github.com/meteoric/ionic-sass/issues/2

also there were problems with it not supporting windows as he is using [LibSass](https://github.com/fourseven/meteor-scss#libsass-vs-ruby-sass)

some of these things maybe fixed now, but i still have an allergy to that package, esp when stylus seems more elegant anyway. 

anyhow, i guess its not a huge issue either way but i just don't see the benefit of going with sass
