### ISSUE TITLE
Anyone can delete a channel

### ISSUE THREAD

**Issue by rclai** [SpaceTalk/SpaceTalk#27]
https://github.com/SpaceTalk/SpaceTalk/blob/fe586b12f9226379f1ab7c9b5b44b0a520f50b6d/server/methods/channels/remove.js

Also are we using methods or minimongo + meteor.allow rules @timbrandin @dstollie .

https://trello.com/c/PbRfcm5M/66-use-methods-or-minimongo-for-writes-or-both-depending-on-use-case

In addition should we use matb33:collection-hooks to be deleting messages when channels are deleted?

I would rather use minimongo to delete it and use meteor.allow rules to first check if this user can delete this channel than checking in the method.

**Comment by ramsaylanier** [comment]
It seems that something like deleting a channel should be something we use a meteor method for. I think using collection-hooks is a good idea - probably easier in the long run than manually updating collections when a dependency is altered.

**Comment by adamdawkins** [comment]
It was agreed that anyone can delete for now; but that should be updated in
the future. Either channels can only be deleted when everyone has left the
channel, or by the creator and/or an admin...

By using collection-hooks, do you mean having messages for a channel
automatically deleted when the channel is?

**Comment by ramsaylanier** [comment]
Yes, collection-hooks give you the ability to perform some function after you create/update/delete items in a collection. So, you can write an after.update hook that takes that channel id and deletes all messages with the channel id. 

See here: https://github.com/matb33/meteor-collection-hooks#afterupdateuserid-doc-fieldnames-modifier-options

**Comment by ramsaylanier** [comment]
https://github.com/matb33/meteor-collection-hooks

**Comment by adamdawkins** [comment]
Cool, anyone can take this on, or you can assign it to me to improve the
remove function. Probably won't get back on it until next week now though.

On 21 May 2015 at 15:14, Ramsay Lanier notifications@github.com wrote:

> https://github.com/matb33/meteor-collection-hooks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SpaceTalk/SpaceTalk/issues/27#issuecomment-104290930.

## 

Adam Dawkins | 07841763735

Adam Dawkins Ltd is a company registered in England and Wales. Registered
Number: 8294660. Registered Address: Adam Dawkins Ltd, Unit 36, 88-90
Hatton Garden, Holborn, London EC1N 8PG

**Comment by ramsaylanier** [comment]
I can take care of it sometime in the next day or two.

**Comment by ramsaylanier** [comment]
So, to be clear, we are checking that either a) the channel is empty or b) it's deleted by an admin/creator?  So an empty channel can be deleted by anyone?

**Comment by adamdawkins** [comment]
I think that was going to be left out of 0.1, probably worth a trello card
for that.

**Comment by ramsaylanier** [comment]
okay so right now I'll just make sure to add collection-hooks and then remove messages associated with the channel

**Comment by rclai** [comment]
Let's put collection hooks on a separate thread. We'll deal with roles later.
