### ISSUE TITLE
Error while running SpaceTalk on windows. No windows compatible build for fourseven:scss@3.0.0.

### ISSUE THREAD

**Issue by dmitrijs-balcers** [SpaceTalk/SpaceTalk#29]
After starting up the app encountered with the following error

```
[[[[[ C:\Users\dmitrijsbalcers\Documents\GitHub\SpaceTalk ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While checking for fourseven:scss@3.0.0:
   error: No compatible binary build found for this package. Contact the
   package author and ask them to publish it for your platform.

=> Your application has errors. Waiting for file change.
```

The version of the package should be changed to the 3.1.1. At the moment, I cannot apply the fix due to an issue described here - https://github.com/SpaceTalk/SpaceTalk/issues/28

**Comment by dstollie** [comment]
is this already fixed @dmitrijs-balcers ?

**Comment by dmitrijs-balcers** [comment]
@dstollie No not yet. I've tried to run _meteor update_ and it seems like app is running, and I can access it. But I do not know why, but there are no styles applied to the app.

![image](https://cloud.githubusercontent.com/assets/2266310/7785453/4dc3d970-0199-11e5-951a-afe2f54a1032.png)

Corresponding commit: https://github.com/dmitrijs-balcers/SpaceTalk/commit/3acae2138a31f187b1bb0fc9957005f62ffa3a5a

File _client/css/main.scss_ was altered after running the _meteor_ command. I don't understand why this file is being modified on running the meteor app.

**Comment by dmitrijs-balcers** [comment]
Found the solution, will push fix soon.

The problem was in scss.json configuration file. Provided path was not Windows env compatible.

**Comment by dmitrijs-balcers** [comment]
All issues related to Windows seems to be resoved. This issue can be closed.
