### ISSUE TITLE
Improve .editorconfig and add .jshintrc

### ISSUE THREAD

**Issue by rclai** [SpaceTalk/SpaceTalk#47]
Let's use this:
https://github.com/raix/Meteor-jshintrc/blob/master/.editorconfig

As well as this:
https://github.com/raix/Meteor-jshintrc/blob/master/.jshintrc

**Comment by dstollie** [comment]
I am getting the use strict error, when I start using this jshnit config file.. could you check that out?

**Comment by rclai** [comment]
Try it now.
