### ISSUE TITLE
Add pinned messages feature

### ISSUE THREAD

**Issue by adamdawkins** [SpaceTalk/SpaceTalk#65]
https://trello.com/c/f5vprsnB/73-pin-messages

**Comment by adamdawkins** [comment]
After discussion in Slack, going to store the pinnedMessageIds on the channel.

**Comment by dalerka** [comment]
I believe this functionality should be implemented as a standalone package:  
1. Similar to `{{> loginButtons}}` a **pinnable Thing** in the UI should have a `{{> pinButton}}` in that Thing's _html template_ ;  
2. When a _pinButton_ is clicked the package should add the **ID** of the relevant document to some array and keep it in some collection, e.g. **Pinned Things**, like:  
`{channel: channel_Id; pinnedThings: [array of pinned things]}`  
3. The package should expose another helper component which will list the **Pinned Things** for ex. via 
`{{> ShowPinnedThingsButton}}` which will trigger another component (a template) to actually display the currently pinned things where appropriate in the DOM (or in a modal) via `{{> PinnedThingsList}}`;  
4. Each of the items listed in the _PinnedThingsList_ will be wrapped in some template, e.g. `templateForItemInPinnedThingsList: myPinnedItemTemplate` defined in a JSON config for the package and such template should have `{{> unpinButton}}` injected and a developer (or a theming package) should be able to customize the look (CSS) of such template.  
5. Of course we'll need to figure out how to cross-reference the _Pinned Things_ in a _Channel_ and other things, I guess.  
6. Similar approach but **per User** could be implemented for **Favorited Things** package.  

Sorry if this already was/should be discussed elsewhere, and I'd love to have any comments  :)

**Comment by adamdawkins** [comment]
@dalerka That sounds great, for now I've just tried to get pinned _Messages_ working. But it could be improved on. I think my PR (#100) might still be worth including as a starting point, as a lot of what I've done could then be abstracted to the approach you mention here.

**Comment by dalerka** [comment]
@adamdawkins, sure, great job! I've learned quite a few things from your commits - thank you! Simpler is better :)
