### ISSUE TITLE
What format should the 'event' variable take in client events

### ISSUE THREAD

**Issue by adamdawkins** [SpaceTalk/SpaceTalk#66]
I've noticed a few different versions of the event variable already:

We've got:

```
function (e) { ... }

function (event) {...}

function (event, template) { ... } // admittedly me, and probably not common or necessary

```

The Meteor Style Guide doesn't give a preference here, but it should be consistent.

**Comment by rclai** [comment]
It should be event.

**Comment by rclai** [comment]
It's not in their style guide, but it is in their contribution guide.

**Comment by rclai** [comment]
One thing to take note of is that Blaze Components event handlers don't have the second argument being the template instance.

`this` is the template instance.
