### ISSUE TITLE
emojione.com - Open source emoji designed for the web

### ISSUE THREAD

**Issue by dstollie** [SpaceTalk/SpaceTalk#68]
Instead of the current emoji library we should pick this one I think. I like the visual graphics of the icons more. 

http://emojione.com/demo

What do you guys think?

**Comment by shtefcs** [comment]
hehe, nice , just wanted to post that one to. I like them, design is flat and modern, they support all devices.

**Comment by rclai** [comment]
Cool, are they resizable though? The demo shows them kind of big. I don't know much about SVGs.

**Comment by dstollie** [comment]
@shtefcs I got it from nullchat from a message of yours! Are you willing to create a pr for this?

**Comment by shtefcs** [comment]
@dstollie hehe, cool :). I would like to do it, but I am not developer ... -.-

**Comment by ramsaylanier** [comment]
Emojione is awesome and there is a meteor package for it. Emoji are
resizebale and sent based on font size.

**Comment by rclai** [comment]
Cool.

**Comment by shtefcs** [comment]
Didnt came to my mind there is meteor package already, tnx for share.
https://github.com/qnub/emojione/

**Comment by dstollie** [comment]
woot gonna implement this!

**Comment by jonearley** [comment]
@dstollie are you going to work on this? I could if you are not already.

**Comment by jonearley** [comment]
Look pretty straightforward so I just went an made a pull request. I am going to try and implement short hand auto-complete soon (http://git.emojione.com/demos/autocomplete.html).

**Comment by ramsaylanier** [comment]
+1 yeah emoji!
