### ISSUE TITLE
Get @mitar's feedback on Blaze Components usage

### ISSUE THREAD

**Issue by rclai** [SpaceTalk/SpaceTalk#71]
@mitar, it would be great if you share with us your opinions/feedback/answer questions about how we've been using Blaze Components.

Contributors, feel free to ask questions and share concerns about the usage of Blaze Components.

**Comment by mitar** [comment]
Sure. Feel free to ask any questions. I will try to answer them.

**Comment by mitar** [comment]
I have not read the code, but one general thing I think is useful is to create a custom base component class you then use all around the project to which you can add base methods you want to use and are maybe missing from barebone core.

Also, use namespaces.

In general, I would recommend that the whole project is using just packages. The project directories become quite unwieldy as project grows. So have a directory `packages` and then separate all the features into separate packages. And then you can control easier the order of files. And also you can do tests for each package separately.

**Comment by adamdawkins** [comment]
Hi @mitar, so here's what we're (I am) trying to do.

We've got a `ChannelInfo` Component for the Info panel. In the `Channel` component, we want to toggle the show/hide of that info bar.

The current develop branch just does this with jquery:

``` js
  events: function () {
    return [
       {
        // ...
       'click [data-action="display-channel-info"]': function (event) {
          event.preventDefault();
          $('.channel-info').toggleClass('channel-info-out');
          $('.channel-content').toggleClass('channel-content-full');
          $('.channel-footer').toggleClass('channel-footer-full');
        }
      }];
  }
```

Then, in a `Message` component, when a message is pinned, we _also_ want to show the channel info bar. What we'd like to do, is have some functions on the `ChannelInfo` component that we can call from these other components, e.g.

``` js
   'click [data-action="pin-message"]': function (event) {
          event.preventDefault();
          ChannelInfo.show()
   }
```

Is this where mixins should come in?

**Comment by MatejJan** [comment]
Hey (I'm from the Blaze Components team too),

I don't think you need a mixin in this case. Here it seems you're just trying to control wether the channel info is shown. 

So the way we're doing these kind of things is like this (let me know if you want more details):
1. Have a reactive var that holds a boolean to show the content:.
   
   ```
   @visible = new ReactiveVar false
   ```
2. Have a method that outputs the class name you'll use in the template to control if something is visible. It would look something like:
   
   ```
   visibleClass: ->
     'visible' if @visible.get()
   ```
   
   You then use this in the template like 
   
   ```
   <div class="panel {{visibleClass}}">
   ```
3. Have a method on the component that can show/hide the content. This can be either two separate methods (`hide`/`show`) although we usually have one like:
   
   ```
   setVisible: (visible) ->
     @visible.set visible
   ```

**Comment by dstollie** [comment]
@Retronator thanks for your response @adamdawkins Is this tip already implemented in your case?

**Comment by adamdawkins** [comment]
@dstollie Yes very similar, we're using ReactiveVars in an 'App' utility:

https://github.com/SpaceTalk/SpaceTalk/blob/feature/pinned-items/client/lib/app.js
