### ISSUE TITLE
styles are missing on windows

### ISSUE THREAD

**Issue by anbuselvan** [SpaceTalk/SpaceTalk#81]
tried SpaceTalk on windows and the styles are not getting reflected.

**Comment by anbuselvan** [comment]
Please refer this PR for full story.
https://github.com/SpaceTalk/SpaceTalk/pull/79

**Comment by rclai** [comment]
@dstollie didn't you address this already?

**Comment by dstollie** [comment]
nope I didnt, I will check this issue in the upcomming weekend if its still not fixed
