### ISSUE TITLE
Add "forgot password?"

### ISSUE THREAD

**Issue by jonearley** [SpaceTalk/SpaceTalk#90]

**Comment by timbrandin** [comment]
Yeah I wonder where it has disappeared

**Comment by rclai** [comment]
Change this to true:
https://github.com/SpaceTalk/SpaceTalk/blob/develop/lib/accounts.js#L16
I'll do it.

**Comment by rclai** [comment]
Can you check if it works?

**Comment by timbrandin** [comment]
@rclai sure :)

**Comment by timbrandin** [comment]
@rclai somethings not working, can't click the reset password link, nothing is happening :s

**Comment by timbrandin** [comment]
Here's a solution #93

**Comment by timbrandin** [comment]
Solved!

**Comment by rclai** [comment]
Ah okay.
