### ISSUE TITLE
Improve channel info panel toggling

### ISSUE THREAD

**Issue by rclai** [SpaceTalk/SpaceTalk#94]
https://github.com/SpaceTalk/SpaceTalk/blob/develop/client/views/channel-info/channel-info.html#L10

Is there a way to not use checkboxes? I find that sometimes I can't get it to expand unless I click just the right spot. I should be able to click that entire block where the heading is to expand it.

**Comment by adamdawkins** [comment]
I'm going to handle this as part of #65, I'm going to move them to a click event on the whole section heading.
