### ISSUE TITLE
Editing a message with emoji doesn't display emoji list if we want to choose a new one

### ISSUE THREAD

**Issue by nabiltntn** [SpaceTalk/SpaceTalk#99]
and when the emoji is the last element in the message, delete and edit icons are misplaced

**Comment by timbrandin** [comment]
I noticed this too. I'm looking at it

**Comment by timbrandin** [comment]
I'm not sure I can add the emoji in edit mode. but the CSS bug is doable before the release

**Comment by timbrandin** [comment]
Can't figure out why images don't affect the width calculation..

**Comment by timbrandin** [comment]
I made a small bugfix when there is one smiley only, it will work but we need to find a better solution to it later.

**Comment by timbrandin** [comment]
Ah I found the issue, we need to use inline-block for the cursor to discover the end of the line if it ends with an image.

**Comment by timbrandin** [comment]
Solved in latest 3d825c4710f49f948e490beaa2017c673787a66a
